{% set name = "regolith" %}
{% set version = "0.6.2" %}
{% set sha256 = "231afb1894f876ef22bdd99de41abee0f0736420a5075edac97a3fd3d561d95b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/scopatz/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python >=3.5
    - pip
    - xonsh
  run:
    - python >=3.5
    - flask
    - jinja2
    - docutils
    - bibtexparser
    - ruamel.yaml
    - cerberus
    - xonsh
    - openpyxl
    - nameparser

test:
  commands:
    - regolith -h
    - regolith build -h
    - regolith validate -h
  imports:
    - regolith

about:
  home: http://scopatz.github.io/regolith-docs/
  license: CC0
  license_file: LICENSE
  summary: 'Research Group Content Managment System'
  dev_url: https://github.com/scopatz/regolith

extra:
  recipe-maintainers:
    - scopatz
    - CJ-Wright
