{%- set name = "regolith" -%}
{%- set version = "0.9.1" -%}
{%- set sha256 = "6e1a535e8dea50ec4f17a76b66fb0d66d70a0e88728c77ed0f684d92abf3283f" -%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regolith/regolith-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  preserve_egg_dir: true
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip

  run:
    - python >=3.10
    - setuptools
    - ruamel.yaml
    - bibtexparser
    - docutils
    - python-dateutil
    - jinja2
    - cerberus
    - flatten-dict
    - xonsh
    - rever
    - openpyxl
    - nameparser
    - pandas
    - pymongo
    - matplotlib-base
    - habanero
    - google-api-python-client
    - goole-auth-oauthlib
    - wxpython
    - gooey

test:
  imports:
    - regolith

  requires:
    - flake8
    - mock
    - pytest
    - requests-mock
    - pytest-mock
    - pytest-env
    - coverage
    - codecov

about:
  home: https://github.com/regro/regolith/
  summary: A Research Group Content Management System
  license: 'CC0-1.0'
  license_file: LICENSE.rst
  description: |
    Keep all your info in databases and build reports such as cv, publication list and so on.
  doc_url: http://regro.github.io/regolith/
  dev_url: https://github.com/regro/regolith/

extra:
  recipe-maintainers:
    - sbillinge
